# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 23:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField(default='')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название вашей фотографии')),
                ('text', models.TextField(default='', verbose_name='Расскажите что-нибудь о ней')),
                ('image', models.ImageField(upload_to='', verbose_name='Выберите файл с фотографией')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('tag', models.CharField(default='', max_length=20, verbose_name='Придумайте интересный тэг')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Albums')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
